

overall:
  get:
    summary: List all products
    responses:
      '200':
        description: A list of products
        content:
          application/json:
            schema:
              $ref: '../commons.yml#/schemas/ReturnManyPayload'
              properties:
                data:
                  items:
                    $ref: '#/components/schemas/Product'

  post:
    summary: Create a new product
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './products.yml#/components/schemas/Product'
    responses:
      '201':
        description: Product created successfully
        content:
          application/json:
            schema:
              $ref: '../commons.yml#/schemas/ReturnSinglePayload'
              properties:
                data:
                  $ref: '#/components/schemas/Product'

specific:
  get:
    summary: Get a product by ID
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '200':
        description: Product details
        content:
          application/json:
            schema:
              $ref: '../commons.yml#/schemas/ReturnSinglePayload'
              properties:
                data:
                  $ref: '#/components/schemas/Product'

  put:
    summary: Update a product by ID
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './products.yml#/components/schemas/Product'
    responses:
      '200':
        description: Product updated successfully
        content:
          application/json:
            schema:
              $ref: '../commons.yml#/schemas/ReturnSinglePayload'
              properties:
                data:
                  $ref: '#/components/schemas/Product'

  delete:
    summary: Delete a product by ID
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '204':
        description: Product deleted successfully
        content:
          application/json:
            schema:
              $ref: '../commons.yml#/schemas/ReturnSinglePayload'
              properties:
                data:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    InputProduct:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        price:
          type: number
          format: decimal
          minimum: 0
        description:
          type: string
        isFavorite:
          type: boolean
        isOnCart:
          type: boolean
        isLabeled:
          type: boolean
        labelContent:
          type: string
          maxLength: 255
        labelColor:
          type: string
          pattern: ^#[0-9a-f]{6}$
        displayImageId:
          type: integer
      required:
        - name
        - price
        - description
        - isFavorite
        - isOnCart
        - isLabeled
        - labelContent
        - labelColor
        - displayImageId
    ReturnProduct:
      type: object
      properties:
        id:
          type: integer
          format: int64
        key:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 255
        price:
          type: number
          format: decimal
          minimum: 0
        description:
          type: string
        isFavorite:
          type: boolean
        isOnCart:
          type: boolean
        isLabeled:
          type: boolean
        labelContent:
          type: string
          maxLength: 255
        labelColor:
          type: string
          pattern: ^#[0-9a-f]{6}$
        displayImageId:
          type: integer
      required:
        - name
        - price
        - description
        - isFavorite
        - isOnCart
        - isLabeled
        - labelContent
        - labelColor