openapi: 3.0.0
info:
  title: Ecommerce Express API
  description: API for ecommerce platform
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
    description: Local development server

paths:
  /products:
    $ref: './resources/products.yml#/overall'
  /products/{id}:
    $ref: './resources/products.yml#/specific'

components:
  schemas:
    Product:
      $ref: './resources/products.yml#/components/schemas/Product'
